const Property = require("../models/property");
const Category = require("../models/category");
const cloudinary = require("../config/cloudinary");
const {
  success,
  created,
  notFound,
  paginated,
  forbidden,
  badRequest,
} = require("../utils/response");
const { asyncHandler, AppError } = require("../utils/errorHandler");
const streamifier = require("streamifier");

// ─── Cloudinary helpers ───────────────────────────────────────────────────────
const uploadToCloudinary = (buffer, folder = "splendor/properties") =>
  new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      { folder, resource_type: "image" },
      (error, result) => (error ? reject(error) : resolve(result)),
    );
    streamifier.createReadStream(buffer).pipe(stream);
  });

const deleteFromCloudinary = (publicId) =>
  cloudinary.uploader.destroy(publicId);

// ─── Category validation helper ───────────────────────────────────────────────
/**
 * Fetches active category labels for a given kind ("type" | "badge").
 * Used to validate incoming values without hard-coding enums in the model.
 */
const getActiveCategoryLabels = async (kind) => {
  const cats = await Category.find({ kind, isActive: true })
    .select("label")
    .lean();

  if (cats.length > 0) return cats.map((c) => c.label);

  return kind === "type" ? Property.DEFAULT_TYPES : Property.DEFAULT_BADGES;
};
// ─── Pricing helper ───────────────────────────────────────────────────────────
/**
 * Builds the pricing sub-document from request body fields.
 * Supports three pricing modes:
 *   1. Plain price   → { original: N }
 *   2. % discount    → { original: N, discountPercent: X, offerExpiresAt? }
 *   3. Fixed offer   → { original: N, offerPrice: M, offerExpiresAt? }
 *
 * Mutually exclusive: offerPrice and discountPercent cannot both be set.
 */
const buildPricing = (body) => {
  const { price, offerPrice, discountPercent, offerExpiresAt, priceLabel } =
    body;

  if (!price) throw new AppError("price is required", 400);
  if (offerPrice != null && discountPercent != null) {
    throw new AppError(
      "Provide either offerPrice or discountPercent — not both.",
      400,
    );
  }

  return {
    original: Number(price),
    offerPrice: offerPrice != null ? Number(offerPrice) : null,
    discountPercent: discountPercent != null ? Number(discountPercent) : null,
    offerExpiresAt: offerExpiresAt ? new Date(offerExpiresAt) : null,
    label: priceLabel || null, // null → auto-generated by pre-save hook
  };
};

// ─── Query builder ────────────────────────────────────────────────────────────
const buildPropertyQuery = (queryParams, isPublic = true) => {
  const {
    page = 1,
    limit = 12,
    sort = "-isFeatured -createdAt", // featured listings rise to the top
    type,
    badge,
    status,
    minPrice,
    maxPrice,
    search,
    isSoldOut,
    includeHidden, // admin only
    isFeatured,
  } = queryParams;

  const filter = {};

  // Public queries always hide non-visible & non-active listings
  if (isPublic) {
    filter.isVisible = true;
    filter.status = { $in: ["active", "sold"] }; // ← allow sold through
  } else {
    // Authenticated admin/manager: optionally include hidden
    if (includeHidden !== "true") filter.isVisible = true;
    if (status) filter.status = status;
  }

  if (type) filter.type = type;
  if (badge) filter.badge = badge;
  if (isFeatured === "true") filter.isFeatured = true;
  if (isSoldOut === "true") filter.isSoldOut = true;
  if (isSoldOut === "false") filter.isSoldOut = false;

  // Price filters operate on pricing.original for simplicity
  if (minPrice || maxPrice) {
    filter["pricing.original"] = {};
    if (minPrice) filter["pricing.original"].$gte = Number(minPrice);
    if (maxPrice) filter["pricing.original"].$lte = Number(maxPrice);
  }

  if (search) filter.$text = { $search: search };

  const skip = (Number(page) - 1) * Number(limit);
  return { filter, sort, skip, limit: Number(limit), page: Number(page) };
};

// ─── GET /api/v1/properties ───────────────────────────────────────────────────
const getProperties = asyncHandler(async (req, res) => {
  const isPublic = !req.user || !["admin", "manager"].includes(req.user.role);
  const { filter, sort, skip, limit, page } = buildPropertyQuery(
    req.query,
    isPublic,
  );

  const [properties, total] = await Promise.all([
    Property.find(filter)
      .populate("listedBy", "firstName lastName email")
      .sort(sort)
      .skip(skip)
      .limit(limit)
      .lean({ virtuals: true }),
    Property.countDocuments(filter),
  ]);

  return paginated(
    res,
    { properties },
    { page, limit, total, pages: Math.ceil(total / limit) },
  );
});

// ─── GET /api/v1/properties/:id ───────────────────────────────────────────────
const getProperty = asyncHandler(async (req, res) => {
  const property = await Property.findByIdAndUpdate(
    req.params.id,
    { $inc: { viewCount: 1 } },
    { new: true },
  )
    .populate("listedBy", "firstName lastName email phone")
    .lean({ virtuals: true });

  if (!property) return notFound(res, "Property not found.");

  // Hide non-visible properties from the public
  if (
    !property.isVisible &&
    (!req.user || !["admin", "manager"].includes(req.user.role))
  ) {
    return notFound(res, "Property not found.");
  }

  return success(res, { property });
});

// ─── POST /api/v1/properties ──────────────────────────────────────────────────
const createProperty = asyncHandler(async (req, res) => {
  const {
    name,
    location,
    beds,
    baths,
    area,
    type,
    badge,
    description,
    features,
    isFeatured,
    featuredUntil,
    coordinates,
  } = req.body;

  // Validate type & badge against dynamic categories
  const [validTypes, validBadges] = await Promise.all([
    getActiveCategoryLabels("type"),
    getActiveCategoryLabels("badge"),
  ]);

  if (!validTypes.includes(type)) {
    return badRequest(
      res,
      `Invalid property type. Valid types: ${validTypes.join(", ")}`,
    );
  }
  if (badge && !validBadges.includes(badge)) {
    return badRequest(
      res,
      `Invalid badge. Valid badges: ${validBadges.join(", ")}`,
    );
  }

  // Build pricing
  let pricing;
  try {
    pricing = buildPricing(req.body);
  } catch (err) {
    return badRequest(res, err.message);
  }

  // Upload images
  const images = req.files?.length
    ? await Promise.all(
        req.files.map(async (file, idx) => {
          const result = await uploadToCloudinary(file.buffer);
          return {
            url: result.secure_url,
            publicId: result.public_id,
            isPrimary: idx === 0,
          };
        }),
      )
    : [];

  const property = await Property.create({
    name,
    location,
    beds,
    baths,
    area,
    type,
    badge: badge || "New Listing",
    description,
    features: features
      ? Array.isArray(features)
        ? features
        : JSON.parse(features)
      : [],
    pricing,
    images,
    isFeatured: isFeatured === "true" || isFeatured === true || false,
    featuredUntil: featuredUntil ? new Date(featuredUntil) : null,
    coordinates: coordinates ? JSON.parse(coordinates) : undefined,
    listedBy: req.user._id,
  });

  return created(res, { property }, "Property listed successfully.");
});

// ─── PATCH /api/v1/properties/:id ─────────────────────────────────────────────
const updateProperty = asyncHandler(async (req, res) => {
  const property = await Property.findById(req.params.id);
  if (!property) return notFound(res, "Property not found.");

  const isAdminOrManager = ["admin", "manager"].includes(req.user.role);
  if (
    !isAdminOrManager &&
    property.listedBy.toString() !== req.user._id.toString()
  ) {
    return forbidden(res, "You are not authorised to edit this property.");
  }

  // ── Validate type/badge if changed ────────────────────────────────────────
  if (req.body.type || req.body.badge) {
    const [validTypes, validBadges] = await Promise.all([
      getActiveCategoryLabels("type"),
      getActiveCategoryLabels("badge"),
    ]);
    if (req.body.type && !validTypes.includes(req.body.type)) {
      return badRequest(
        res,
        `Invalid property type. Valid: ${validTypes.join(", ")}`,
      );
    }
    if (req.body.badge && !validBadges.includes(req.body.badge)) {
      return badRequest(res, `Invalid badge. Valid: ${validBadges.join(", ")}`);
    }
  }

  // ── Simple scalar fields ───────────────────────────────────────────────────
  const scalarFields = [
    "name",
    "location",
    "beds",
    "baths",
    "area",
    "type",
    "badge",
    "description",
    "features",
    "status",
    "isFeatured",
    "featuredUntil",
  ];
  scalarFields.forEach((field) => {
    if (req.body[field] !== undefined) property[field] = req.body[field];
  });

  // ── Visibility toggle ─────────────────────────────────────────────────────
  if (req.body.isVisible !== undefined) {
    property.isVisible =
      req.body.isVisible === "true" || req.body.isVisible === true;
  }

  // ── Sold Out toggle ───────────────────────────────────────────────────────
  if (req.body.isSoldOut !== undefined) {
    const soldOut =
      req.body.isSoldOut === "true" || req.body.isSoldOut === true;
    property.isSoldOut = soldOut;
    if (soldOut && !property.soldAt) property.soldAt = new Date();
    if (!soldOut) property.soldAt = null;
  }

  // ── Pricing update ─────────────────────────────────────────────────────────
  // Only rebuild if any pricing field is present in the request
  const pricingFields = [
    "price",
    "offerPrice",
    "discountPercent",
    "offerExpiresAt",
    "priceLabel",
  ];
  const hasPricingUpdate = pricingFields.some((f) => req.body[f] !== undefined);
  if (hasPricingUpdate) {
    try {
      // Merge with existing so partial updates work
      const merged = {
        price: req.body.price ?? property.pricing.original,
        offerPrice:
          req.body.offerPrice !== undefined
            ? req.body.offerPrice
            : property.pricing.offerPrice,
        discountPercent:
          req.body.discountPercent !== undefined
            ? req.body.discountPercent
            : property.pricing.discountPercent,
        offerExpiresAt:
          req.body.offerExpiresAt !== undefined
            ? req.body.offerExpiresAt
            : property.pricing.offerExpiresAt,
        priceLabel:
          req.body.priceLabel !== undefined
            ? req.body.priceLabel
            : property.pricing.label,
      };

      // Allow clearing a discount explicitly
      if (req.body.clearOffer === "true") {
        merged.offerPrice = null;
        merged.discountPercent = null;
        merged.offerExpiresAt = null;
        merged.priceLabel = null;
      }

      property.pricing = buildPricing(merged);
    } catch (err) {
      return badRequest(res, err.message);
    }
  }

  // ── New image uploads ──────────────────────────────────────────────────────
  if (req.files?.length) {
    const newImages = await Promise.all(
      req.files.map(async (file) => {
        const result = await uploadToCloudinary(file.buffer);
        return { url: result.secure_url, publicId: result.public_id };
      }),
    );
    property.images.push(...newImages);
  }

  await property.save();
  return success(
    res,
    { property: property.toObject({ virtuals: true }) },
    "Property updated.",
  );
});

// ─── PATCH /api/v1/properties/:id/visibility ─────────────────────────────────
// Dedicated quick-toggle endpoint for the admin dashboard
const toggleVisibility = asyncHandler(async (req, res) => {
  const property = await Property.findById(req.params.id);
  if (!property) return notFound(res, "Property not found.");

  property.isVisible = !property.isVisible;
  await property.save();

  return success(
    res,
    { isVisible: property.isVisible },
    `Property is now ${property.isVisible ? "visible" : "hidden"}.`,
  );
});

// ─── PATCH /api/v1/properties/:id/sold-out ───────────────────────────────────
const toggleSoldOut = asyncHandler(async (req, res) => {
  const property = await Property.findById(req.params.id);
  if (!property) return notFound(res, "Property not found.");

  property.isSoldOut = !property.isSoldOut;
  if (property.isSoldOut) {
    property.soldAt = new Date();
    property.status = "sold";
  } else {
    property.soldAt = null;
    property.status = "active";
  }

  await property.save();
  return success(
    res,
    { isSoldOut: property.isSoldOut, status: property.status },
    `Property marked as ${property.isSoldOut ? "sold out" : "available"}.`,
  );
});

// ─── PATCH /api/v1/properties/:id/offer ──────────────────────────────────────
// Quick offer endpoint — add or remove an offer without touching other fields
const setOffer = asyncHandler(async (req, res) => {
  const property = await Property.findById(req.params.id);
  if (!property) return notFound(res, "Property not found.");

  const { discountPercent, offerPrice, offerExpiresAt, clearOffer } = req.body;

  if (clearOffer === true || clearOffer === "true") {
    property.pricing.offerPrice = null;
    property.pricing.discountPercent = null;
    property.pricing.offerExpiresAt = null;
    property.pricing.label = null; // regenerated by pre-save hook
  } else {
    if (offerPrice != null && discountPercent != null) {
      return badRequest(
        res,
        "Provide either offerPrice or discountPercent — not both.",
      );
    }
    if (offerPrice != null) property.pricing.offerPrice = Number(offerPrice);
    if (discountPercent != null)
      property.pricing.discountPercent = Number(discountPercent);
    if (offerExpiresAt)
      property.pricing.offerExpiresAt = new Date(offerExpiresAt);
    property.pricing.label = null; // force regeneration
  }

  property.markModified("pricing");
  await property.save();

  return success(
    res,
    { pricing: property.toObject({ virtuals: true }).pricing },
    clearOffer ? "Offer removed." : "Offer applied.",
  );
});

// ─── DELETE /api/v1/properties/:id ───────────────────────────────────────────
const deleteProperty = asyncHandler(async (req, res) => {
  const property = await Property.findById(req.params.id);
  if (!property) return notFound(res, "Property not found.");

  if (property.images?.length) {
    await Promise.all(
      property.images.map((img) => deleteFromCloudinary(img.publicId)),
    );
  }

  await property.deleteOne();
  return success(res, {}, "Property deleted.");
});

// ─── DELETE /api/v1/properties/:id/images/:imageId ───────────────────────────
const removePropertyImage = asyncHandler(async (req, res) => {
  const property = await Property.findById(req.params.id);
  if (!property) return notFound(res, "Property not found.");

  const image = property.images.id(req.params.imageId);
  if (!image) return notFound(res, "Image not found.");

  await deleteFromCloudinary(image.publicId);

  property.images = property.images.filter(
    (img) => img._id.toString() !== req.params.imageId,
  );
  await property.save();
  return success(res, { property }, "Image removed.");
});

module.exports = {
  getProperties,
  getProperty,
  createProperty,
  updateProperty,
  toggleVisibility,
  toggleSoldOut,
  setOffer,
  deleteProperty,
  removePropertyImage,
};
