export const properties = [
  {
    id: 1,
    name: "Amalia Springs",
    location: "Kiamiti Road, Nairobi",
    price: "KES 24.5M",
    beds: 4,
    baths: 5,
    area: 350,
    type: "Villa",
    badge: "Featured",
    badgeColor: "#0d6e5e",
    rating: 4.95,
    reviews: 62,
    yearBuilt: 2021,
    floors: 3,
    garage: 2,
    status: "Ready",
    agent: {
      name: "James Kariuki",
      initials: "JK",
      role: "Luxury Property Specialist · Nairobi",
    },
    description:
      "Amalia Springs is a breathtaking villa nestled along Kiamiti Road, designed for those who demand the finest in modern living. Featuring soaring ceilings, bespoke finishes, and a private landscaped garden, this is a rare opportunity to own one of Nairobi's most coveted addresses. The open-plan living spaces flow seamlessly onto a shaded terrace overlooking a private pool, perfect for entertaining or unwinding in total privacy.",
    imgs: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&q=80",
      "https://images.unsplash.com/photo-1565182999561-18d7dc61c393?w=800&q=80",
      "https://images.unsplash.com/photo-1501183638710-841dd1904471?w=800&q=80",
    ],
    amenities: [
      "Private Swimming Pool",
      "Landscaped Garden",
      "Home Theatre",
      "Chef's Kitchen",
      "Smart Home System",
      "Solar Power",
      "Borehole & Pump",
      "Staff Quarters",
      "Electric Fence",
      "CCTV Surveillance",
      "Ample Parking",
      "Backup Generator",
      "Fiber Optic Network",
      "Gym",
      "Wine Cellar",
      "Laundry Room",
    ],
    pricing: [
      {
        unit: "4 Bedroom Villa",
        size: "350",
        dsq: "40 sqm",
        price: "KES 24.5M",
      },
    ],
  },

  {
    id: 2,
    name: "Palm Court",
    location: "Ruguima, Kenya",
    price: "KES 22M",
    beds: 5,
    baths: 5,
    area: 280,
    type: "Townhouse",
    badge: "New Listing",
    badgeColor: "#c2410c",
    rating: 4.87,
    reviews: 39,
    yearBuilt: 2023,
    floors: 3,
    garage: 2,
    status: "Ready",
    agent: {
      name: "Amina Hassan",
      initials: "AH",
      role: "Senior Property Consultant · Nairobi",
    },
    description:
      "Palm Court is an elegantly designed townhouse community in the lush Ruguima corridor, offering spacious family homes with premium finishes throughout. Each unit features a private rooftop terrace, double garage, and generous living areas that blend indoor and outdoor living. Situated within a secure, gated estate with 24-hour security and resort-style communal amenities.",
    imgs: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=900&q=80",
      "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=800&q=80",
      "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80",
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    ],
    amenities: [
      "Rooftop Terrace",
      "Double Garage",
      "Swimming Pool",
      "Children's Play Area",
      "Clubhouse",
      "Jogging Track",
      "24/7 Security",
      "CCTV Surveillance",
      "Backup Generator",
      "Borehole & Pump",
      "Fiber Optic Network",
      "Landscaped Gardens",
    ],
    pricing: [
      {
        unit: "5 Bedroom Townhouse",
        size: "280",
        dsq: "30 sqm",
        price: "KES 22M",
      },
    ],
  },

  {
    id: 3,
    name: "143 Brookview",
    location: "Ruru, Nairobi",
    price: "KES 33M",
    beds: 4,
    baths: 4,
    area: 250,
    type: "Apartment",
    badge: "New Listing",
    badgeColor: "#c2410c",
    rating: 4.92,
    reviews: 55,
    yearBuilt: 2022,
    floors: 12,
    garage: 1,
    status: "Ready",
    agent: {
      name: "David Otieno",
      initials: "DO",
      role: "Premium Apartments Specialist · Nairobi",
    },
    description:
      "143 Brookview redefines high-rise luxury in Nairobi. Perched in the serene Ruru neighbourhood, this architecturally stunning development offers panoramic city views from every floor. The interiors are finished with Italian marble, bespoke cabinetry, and floor-to-ceiling glass that floods every room with natural light. A rare opportunity in one of Nairobi's fastest-appreciating postcodes.",
    imgs: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80",
      "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?w=800&q=80",
    ],
    amenities: [
      "Panoramic City Views",
      "Concierge Service",
      "Rooftop Pool",
      "Gym & Spa",
      "Underground Parking",
      "Elevator",
      "Smart Home System",
      "24/7 Security",
      "Fiber Optic Network",
      "Backup Generator",
      "Conference Room",
      "Lounge",
    ],
    pricing: [
      { unit: "3 Bedroom", size: "190", dsq: "—", price: "KES 24M" },
      { unit: "4 Bedroom", size: "250", dsq: "25 sqm", price: "KES 33M" },
      { unit: "Penthouse", size: "380", dsq: "35 sqm", price: "KES 55M" },
    ],
  },

  {
    id: 4,
    name: "Grosvenor",
    location: "Westlands, Nairobi",
    price: "KES 8.8M",
    beds: 1,
    baths: 1,
    area: 56,
    type: "Apartment",
    badge: "Featured",
    badgeColor: "#0d6e5e",
    rating: 4.78,
    reviews: 31,
    yearBuilt: 2020,
    floors: 8,
    garage: 1,
    status: "Ready",
    agent: {
      name: "Sarah Mwangi",
      initials: "SM",
      role: "Senior Property Consultant · Nairobi",
    },
    description:
      "Grosvenor offers sophisticated urban living in the heart of Westlands, Nairobi's most vibrant commercial and lifestyle district. Designed for the modern professional, this development combines contemporary architecture with thoughtful interior design. Steps from the best restaurants, retail, and business parks in the city, Grosvenor is the ideal urban sanctuary.",
    imgs: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80",
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
      "https://images.unsplash.com/photo-1574643156929-51fa098b0394?w=800&q=80",
    ],
    amenities: [
      "Concierge Service",
      "Rooftop Garden",
      "Gym",
      "Swimming Pool",
      "Secure Parking",
      "Elevator",
      "24/7 Security",
      "CCTV Surveillance",
      "Backup Generator",
      "Fiber Optic Network",
      "Laundry Facilities",
    ],
    pricing: [
      { unit: "Studio", size: "38", dsq: "—", price: "KES 5.5M" },
      { unit: "1 Bedroom", size: "56", dsq: "—", price: "KES 8.8M" },
      { unit: "2 Bedroom", size: "95", dsq: "—", price: "KES 14M" },
    ],
  },

  {
    id: 5,
    name: "Diamond Ivy",
    location: "Kileleahwa, Nairobi",
    price: "KES 6.8M",
    beds: 1,
    baths: 2,
    area: 60,
    type: "Apartment",
    badge: "Featured",
    badgeColor: "#0d6e5e",
    rating: 4.9,
    reviews: 48,
    yearBuilt: 2022,
    floors: 5,
    garage: 1,
    status: "Off-Plan",
    agent: {
      name: "Sarah Mwangi",
      initials: "SM",
      role: "Senior Property Consultant · Nairobi",
    },
    description:
      "Another beautiful off-plan project that promises amazing investment opportunities and homes, set to be one of the most coveted locations along Mandera Road next to Quickmart, a minute from Kileleahwa Police Station, minutes from Kenya High and the vibrant epicenter of dining and entertainment in Kileleahwa. This development features 1, 2, 3 & 4 bedroom apartments with a wealth of executive amenities.",
    imgs: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    amenities: [
      "Social Club",
      "Coffee Shop",
      "Bar",
      "Garden",
      "Gym",
      "Swimming Pool",
      "Backup Generator",
      "Access Control System",
      "Kids Play",
      "Reception Center",
      "Conference Room",
      "24/7 Hours Security",
      "CCTV Surveillance",
      "Ample Parking",
      "Smart Lock Door Access",
      "Intercom System",
      "Borehole & Pump",
      "Fiber Optic Network",
    ],
    pricing: [
      { unit: "1 Bedroom", size: "60", dsq: "—", price: "KES 6.8M" },
      { unit: "1 Bedroom", size: "78", dsq: "—", price: "KES 7.8M" },
      { unit: "2 Bedrooms", size: "125", dsq: "—", price: "KES 11.5M" },
      { unit: "2 Bedrooms", size: "144", dsq: "—", price: "KES 12.5M" },
      { unit: "2 Bed + Study", size: "163", dsq: "21 sqm", price: "KES 14.5M" },
      { unit: "3 Bedrooms", size: "225", dsq: "21 sqm", price: "KES 19.5M" },
      { unit: "3 Bed + Study", size: "229", dsq: "21 sqm", price: "KES 21.2M" },
      { unit: "4 Bedrooms", size: "238", dsq: "22 sqm", price: "KES 22M" },
      { unit: "4 Bed + Study", size: "289", dsq: "22 sqm", price: "KES 24M" },
    ],
  },

  {
    id: 6,
    name: "Laika Residences",
    location: "Ruaka, Kiambu",
    price: "KES 4.7M",
    beds: 3,
    baths: 2,
    area: 60,
    type: "Maisonette",
    badge: "For Sale",
    badgeColor: "#1d4ed8",
    rating: 4.83,
    reviews: 27,
    yearBuilt: 2023,
    floors: 2,
    garage: 1,
    status: "Ready",
    agent: {
      name: "Peter Njoroge",
      initials: "PN",
      role: "Property Consultant · Kiambu",
    },
    description:
      "Laika Residences is a charming maisonette development in the rapidly growing Ruaka corridor, offering affordable family homes without compromising on quality. Each unit is thoughtfully designed with an open-plan ground floor, three generous bedrooms upstairs, and a private rear garden. Situated minutes from the Northern Bypass and Ruaka town, with excellent access to Nairobi's CBD and Westlands.",
    imgs: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80",
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80",
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
      "https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=800&q=80",
    ],
    amenities: [
      "Private Garden",
      "Secure Perimeter Wall",
      "Ample Parking",
      "Borehole & Pump",
      "Solar Water Heating",
      "Backup Generator",
      "Fiber Optic Ready",
      "24/7 Security",
      "CCTV Surveillance",
      "Kids Play Area",
    ],
    pricing: [
      { unit: "3 Bedroom Maisonette", size: "60", dsq: "—", price: "KES 4.7M" },
    ],
  },

  {
    id: 7,
    name: "Shangrila Villa",
    location: "Ongata Rongai, Kajiado",
    price: "KES 20M",
    beds: 4,
    baths: 5,
    area: 200,
    type: "Villa",
    badge: "Featured",
    badgeColor: "#0d6e5e",
    rating: 4.96,
    reviews: 74,
    yearBuilt: 2021,
    floors: 2,
    garage: 2,
    status: "Ready",
    agent: {
      name: "Grace Wanjiku",
      initials: "GW",
      role: "Luxury Homes Specialist · Kajiado",
    },
    description:
      "Shangrila Villa is a masterpiece of contemporary design set within the tranquil landscape of Ongata Rongai. Surrounded by mature trees and manicured grounds, this four-bedroom family home offers the ultimate in private suburban living. The double-volume living room, gourmet kitchen, and seamless indoor-outdoor flow make it perfect for families who love to entertain. Just 20 minutes from Nairobi's CBD via the Southern Bypass.",
    imgs: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80",
      "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80",
      "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80",
    ],
    amenities: [
      "Private Swimming Pool",
      "Landscaped Garden",
      "Double Garage",
      "Smart Home System",
      "Solar Power",
      "Borehole & Pump",
      "Staff Quarters",
      "Electric Fence",
      "CCTV Surveillance",
      "Backup Generator",
      "Gym",
      "Outdoor Kitchen",
      "Fiber Optic Network",
      "Home Theatre",
    ],
    pricing: [
      { unit: "4 Bedroom Villa", size: "200", dsq: "25 sqm", price: "KES 20M" },
    ],
  },

  {
    id: 8,
    name: "Forest Hill",
    location: "Ngong, Kajiado",
    price: "KES 15M",
    beds: 4,
    baths: 4,
    area: 210,
    type: "Townhouse",
    badge: "Featured",
    badgeColor: "#0d6e5e",
    rating: 4.88,
    reviews: 43,
    yearBuilt: 2022,
    floors: 3,
    garage: 2,
    status: "Ready",
    agent: {
      name: "Kevin Maina",
      initials: "KM",
      role: "Property Consultant · Kajiado",
    },
    description:
      "Forest Hill is an exclusive townhouse development nestled in the cool, scenic hills of Ngong, offering a peaceful retreat from the city without sacrificing convenience. Each home benefits from sweeping views of the Ngong Hills, generous room sizes, high-end finishes, and private gardens. The development sits within a secure, professionally managed estate with excellent communal amenities.",
    imgs: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=900&q=80",
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
      "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=800&q=80",
      "https://images.unsplash.com/photo-1560184897-ae75f418493e?w=800&q=80",
      "https://images.unsplash.com/photo-1598228723793-52759bba239c?w=800&q=80",
    ],
    amenities: [
      "Ngong Hills Views",
      "Private Garden",
      "Double Garage",
      "Clubhouse",
      "Swimming Pool",
      "Children's Play Area",
      "Jogging Track",
      "24/7 Security",
      "CCTV Surveillance",
      "Backup Generator",
      "Borehole & Pump",
      "Fiber Optic Network",
    ],
    pricing: [
      {
        unit: "3 Bedroom Townhouse",
        size: "165",
        dsq: "—",
        price: "KES 11.5M",
      },
      {
        unit: "4 Bedroom Townhouse",
        size: "210",
        dsq: "20 sqm",
        price: "KES 15M",
      },
    ],
  },

  {
    id: 9,
    name: "Serene Park",
    location: "Machakos, Kenya",
    price: "KES 22.4M",
    beds: 0,
    baths: 0,
    area: 280,
    type: "Land/Plot",
    badge: "For Sale",
    badgeColor: "#1d4ed8",
    rating: 4.72,
    reviews: 18,
    yearBuilt: null,
    floors: null,
    garage: null,
    status: "Ready to Build",
    agent: {
      name: "John Mutua",
      initials: "JM",
      role: "Land & Investment Specialist · Machakos",
    },
    description:
      "Serene Park is a premium serviced land development set in the fast-growing Machakos County, offering investors and homeowners a rare chance to own a piece of Kenya's most sought-after expansion corridor. The plots are fully serviced with tarmac access roads, electricity, and water, sitting within a secure, surveyed estate. With Machakos' proximity to JKIA and the SGR, this is a prime investment opportunity with strong appreciation potential.",
    imgs: [
      "https://images.unsplash.com/photo-1448630360428-65456885c650?w=900&q=80",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
      "https://images.unsplash.com/photo-1560493676-04071c5f467b?w=800&q=80",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    ],
    amenities: [
      "Tarmac Access Roads",
      "Electricity Connection",
      "Water Supply",
      "Perimeter Wall",
      "Gated Entrance",
      "24/7 Security",
      "Survey & Title Deed",
      "Flexible Payment Plans",
    ],
    pricing: [
      { unit: "1/8 Acre Plot", size: "50", dsq: "—", price: "KES 5.6M" },
      { unit: "1/4 Acre Plot", size: "100", dsq: "—", price: "KES 11.2M" },
      { unit: "1/2 Acre Plot", size: "200", dsq: "—", price: "KES 22.4M" },
    ],
  },
];

export const tabs = [
  "View All",
  "Apartments",
  "Land/Plot",
  "Maisonettes",
  "Townhouse",
  "Villa",
];
